def flutter_ios_podfile_setup
  # Minimal setup hook called from the project's Podfile.
  # Kept intentionally small: the real file is generated by Flutter tooling.
  return
end

def flutter_install_all_ios_pods(flutter_application_path)
  # List of plugin pods used by this project.
  # Keep in sync with pubspec.lock if you add/remove plugins.
  plugin_pods = {
    'shared_preferences_foundation' => 'shared_preferences_foundation'
  }

  plugin_pods.each do |name, relative_path|
    pod name, :path => File.join(flutter_application_path, '.symlinks', 'plugins', relative_path, 'ios')
  end
end

def flutter_additional_ios_build_settings(target)
  # Apply minimal sane defaults for plugin targets.
  target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'NO'
    # Ensure Swift compatibility if any plugin uses Swift
    config.build_settings['SWIFT_VERSION'] ||= '5.0'
  end
end
